In [64]:
import numpy as np

In [2]:
type(np.array(['ola', 2,3]))

numpy.ndarray

In [4]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [5]:
# two dimensional array

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [4]:
x = np.array([(1,2),(3,4)], dtype = [('a', '<i2'),('b', '<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [5]:
type(x[1][0])

numpy.int16

In [8]:
np.asmatrix(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [9]:
a = [1,2]
np.array(a)

array([1, 2])

In [10]:
type(a)

list

In [11]:
np.asarray(a)

array([1, 2])

In [12]:
type(a)

list

In [3]:
np.fromfunction(lambda i, j, k : i * j * k, (3, 3, 3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [7]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000027A0F007780>

In [8]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [9]:
a = np.fromstring('234 234', sep = ' ')
a

array([234., 234.])

In [11]:
np.fromstring('1, 2', dtype = int, sep = ', ')

array([1, 2])

In [12]:
x1 = np.array([1,2,3,4])

In [13]:
x2 = np.array(['a', 'dd', 'xyz', '12'])
x3 = np.array([1.1, 2,3,4])
x4 = np.array([1.1,2,3,4])

In [15]:
r = np._core.records.fromarrays([x1, x2, x3, x4])
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i8'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [16]:
list(range(4,50,2))

[4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [17]:
np.arange(5,16,2.3)   #arange is the same as range in python, the diff is range doesn't generate floating number

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [18]:
print((np.linspace(1,5,50))) # the 50 is not step it is the number of data it will generate between 1 and 5

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [20]:
print(np.zeros((3,4,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [22]:
np.ones((3,5)) * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [23]:
np.empty((3,5))

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [24]:
np.empty((3,5))

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [25]:
mat1 = np.eye(4)
print(mat1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
np.logspace(2.0, 3.0, num=4, base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [27]:
np.linspace(2.0, 3.0, num = 5, retstep =  True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [29]:
 a = np.zeros((3,4,8))
a

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [31]:
(a + 5) * 2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [32]:
b = np.linspace(4,8,80)
b

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [33]:
c = [1,2,3,4,5]
np.matrix(c)

matrix([[1, 2, 3, 4, 5]])

In [44]:
d = np.ones((4,5,2))
print(d)
print(d.shape, d.dtype, d.ndim)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
(4, 5, 2) float64 3


In [48]:
xa = np.ones((3,3,3))
xb = np.ones((3,3,3)) + 5
print(xa)
print(xb)
print(xa * xb)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]]
[[[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]

 [[6. 6. 6.]
  [6. 6. 6.]
  [6. 6. 6.]]]


In [55]:
x = np.arange(16).reshape((-1,4))


In [56]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.diag(x)

array([ 0,  5, 10, 15])

In [58]:
np.diag(x, k =2)

array([2, 7])

In [59]:
 np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [61]:
np.tri(3,5,1, dtype = int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [62]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [67]:
print(np.random.rand(2,3, 8))

[[[0.73702161 0.43726545 0.97972903 0.93298956 0.30096906 0.77972891
   0.40207047 0.58941205]
  [0.75895321 0.34504207 0.77910962 0.55774425 0.28826195 0.57942971
   0.15794107 0.55776845]
  [0.60803377 0.76042515 0.12791524 0.4096419  0.7775383  0.56110275
   0.28496039 0.55738763]]

 [[0.24755763 0.65660469 0.02533901 0.88099256 0.3902258  0.46149624
   0.94396216 0.67686425]
  [0.21476446 0.87301401 0.66441929 0.83082807 0.76489457 0.66136557
   0.70604989 0.76185943]
  [0.33198578 0.88131563 0.57838923 0.55755001 0.87282882 0.43504729
   0.11840041 0.94491824]]]


In [70]:
print(np.random.randint(1,100,(4,4,5)))

[[[34 10 69 68  8]
  [81 39 93 87 36]
  [ 5 21 79 21 90]
  [13 80 21 10 80]]

 [[15 17 15 42 72]
  [55 76 92 57 83]
  [ 2  7 39 94 14]
  [70  1 32 23 32]]

 [[72 20 34 60 67]
  [81 30 75 23 40]
  [13  5 84 99 65]
  [11 21  2 48 27]]

 [[91 30 87 49 83]
  [ 8 23 39  3 76]
  [66  7 69 60 39]
  [35 80 15 52 93]]]


In [69]:
print(np.random.randint(1,7,20))

[1 5 1 3 1 6 4 6 3 4 4 1 1 6 1 1 6 4 2 5]


In [71]:
from numpy.random import randint as ri

In [72]:
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[44, 46, 77, 42, 74],
       [41, 38, 72, 27,  3],
       [77, 30, 31, 18, 45],
       [64, 10, 79, 27,  3],
       [ 1, 27, 77, 84, 74],
       [95, 88, 75, 92, 13]], dtype=int32)

In [73]:
b

array([[[44, 46, 77, 42, 74],
        [41, 38, 72, 27,  3],
        [77, 30, 31, 18, 45]],

       [[64, 10, 79, 27,  3],
        [ 1, 27, 77, 84, 74],
        [95, 88, 75, 92, 13]]], dtype=int32)

In [77]:
A = ri(1,100,10)
print("\n Vector or random integers\n", '-'*50, "\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


 Vector or random integers
 -------------------------------------------------- 
 [46 61 52 69 68 96 28 47 79 99]

Here is the sorted vector
 -------------------------------------------------- 
 [28 46 47 52 61 68 69 79 96 99]


In [79]:
M = ri(1,100,25).reshape(5,5)
M

array([[59, 42, 47, 40, 77],
       [16, 17, 21, 75, 34],
       [17, 55, 59, 45, 99],
       [80, 70, 69, 18, 10],
       [57,  8, 99, 26, 85]], dtype=int32)

In [80]:
N  = np.sort(M, axis = 1)
N

array([[40, 42, 47, 59, 77],
       [16, 17, 21, 34, 75],
       [17, 45, 55, 59, 99],
       [10, 18, 69, 70, 80],
       [ 8, 26, 57, 85, 99]], dtype=int32)

In [82]:
print("Max of a location:", M.argmax(axis = 1))
print("Max of b location:", b.argmax())

Max of a location: [4 3 4 0 2]
Max of b location: 25


In [83]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [88]:
print("3 elements from last backwards are:", arr[-1:7:-1])

3 elements from last backwards are: [10  9  8]


In [89]:
start = np.zeros((4,4))
start = start + 100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [91]:
add_rows = np.array([1,0,2,5])
add_rows

array([1, 0, 2, 5])

In [92]:
y = start + add_rows
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [97]:
#transpose is for rotating data
np.array([0,1,2,3]).T


array([0, 1, 2, 3])